---
title: "Importance Of Handwash expalined via Data"
output: 
  html_notebook: 
    toc: yes
---
```{r}
# Load in the tidyverse package
library(readr)
library(tidyverse)

# Read datasets/yearly_deaths_by_clinic.csv into yearly
yearly <- read_csv("C:/Users/sys/Documents/Dr. Semmelweis and the discovery of handwashing/datasets/yearly_deaths_by_clinic.csv")

# Print out yearly
print(yearly)
```
```{r}
# Adding a new column to yearly with proportion of deaths per no. births
yearly <- mutate(yearly, proportion_deaths = deaths/births)

# Print out yearly
yearly
```
```{r}
library(ggplot2)
# Setting the size of plots in this notebook
options(repr.plot.width=7, repr.plot.height=4)

# Plot yearly proportion of deaths at the two clinics
yearly%>%
    ggplot(aes(x= year, y = proportion_deaths, color = clinic))+
    geom_line()
```
```{r}
# Read datasets/monthly_deaths.csv into monthly
monthly <-read_csv("C:/Users/sys/Documents/Dr. Semmelweis and the discovery of handwashing/datasets/monthly_deaths.csv")

# Adding a new column with proportion of deaths per no. births
monthly <- mutate(monthly, proportion_deaths = deaths/births)

# Print out the first rows in monthly
head(monthly)
```
```{r}
# Plot monthly proportion of deaths
monthly %>%
    ggplot(aes(x=date, y=proportion_deaths))+
    geom_line()+
    labs(x="date", y="Proportion of deaths")
```
```{r}
# From this date handwashing was made mandatory
handwashing_start = as.Date('1847-06-01')

# Add a TRUE/FALSE column to monthly called handwashing_started
monthly <- mutate(monthly, handwashing_started = monthly$date >= handwashing_start)

# Plot monthly proportion of deaths before and after handwashing
monthly %>%
    ggplot(aes(x=date, y=proportion_deaths, color = handwashing_started))+
    geom_line()+
    labs(x="Date", y="Proportion of Deaths")
```
```{r}
# Calculating the mean proportion of deaths 
# before and after handwashing.

monthly_summary <- monthly %>%
                       group_by(handwashing_started)%>%
                       summarise(mean_proportion_deaths = sum(deaths)/sum(births))

# Printing out the summary.
monthly_summary
```
```{r}
# Calculating a 95% Confidence intrerval using t.test 
test_result <- t.test( proportion_deaths ~ handwashing_started, data = monthly)
test_result
```
```{r}
# The data Semmelweis collected points to that:
doctors_should_wash_their_hands <- TRUE
```